export const tagsDataById = {
  // difficulty
  easy: { group: 2, icon: 'grin-beam', color: '#393', custom: false, auto: true },
  normal: { group: 2, icon: 'grimace', color: '#c63', custom: false, auto: true },
  hard: { group: 2, icon: 'dizzy', color: '#933', custom: false, auto: true },
  // physics
  diabotical: { group: 3, icon: 'frog', color: '#696', custom: false, auto: true },
  vintage: { group: 3, icon: 'fish', color: '#68a', custom: false, auto: true },
  race: { group: 3, icon: 'crow', color: '#966', custom: false, auto: true },
  // author
  official: { group: 6, icon: 'check-circle', color: '#090', custom: false },
  community: { group: 6, icon: 'users', color: '#09c', custom: false, auto: true },
  archived: { group: 7, icon: 'archive', color: '#987', custom: false, auto: true },
  // esports
  league: { group: 8, icon: 'trophy', color: '#c90', custom: false },
  eggcup: { group: 8, icon: 'trophy', color: '#c90', custom: false },
  // special
  new: { group: 9, icon: 'calendar-plus', color: '#09c', custom: false, auto: true },
  // tags
  // grenade: { group: 5, icon: 'bomb', color: '#c60' },
  // blaster: { group: 5, icon: 'sun', color: '#609' },
  // rocket: { group: 5, icon: 'rocket', color: '#900' },
  // climb: { group: 5, icon: 'mountain', color: '#960' },
  // slide: { group: 5, icon: 'skating', color: 'hsl(180deg 50% 50%)' }, // /* 'sleigh' */
  // strafe: { group: 5, icon: 'running', color: 'hsl(240deg 50% 50%)' },
  // ctf: { group: 5, icon: 'flag', color: 'hsl(190deg 50% 50%)' },
  // torture: { group: 5, icon: 'fist-raised', color: '#660' },
  // gr: { group: 5, icon: 'coins', color: '#c60' },
  // coins: { group: 5, icon: 'coins', color: '#c60' },
  // 'explosion weeball': { group: 5, icon: 'expand-arrows-alt', color: '#c00' },
  // 'implosion weeball': { group: 5, icon: 'compress-arrows-alt', color: '#c0c' },
} as Record<TTagId, Partial<TTag>> // { group: number; icon: string; color: string }

export const flags = [
  'ad',
  'ae',
  'af',
  'ag',
  'ai',
  'al',
  'am',
  'ao',
  'ar',
  'as',
  'at',
  'au',
  'aw',
  'az',
  'ba',
  'bb',
  'bd',
  'be',
  'bf',
  'bg',
  'bh',
  'bi',
  'bj',
  'bl',
  'bm',
  'bn',
  'bo',
  'bq',
  'br',
  'bs',
  'bt',
  'bw',
  'by',
  'bz',
  'ca',
  'cc',
  'cd',
  'cf',
  'cg',
  'ch',
  'ci',
  'ck',
  'cl',
  'cm',
  'cn',
  'co',
  'cr',
  'cu',
  'cv',
  'cw',
  'cx',
  'cy',
  'cz',
  'de',
  'dj',
  'dk',
  'dm',
  'do',
  'dz',
  'ec',
  'ee',
  'eg',
  'eh',
  'er',
  'es',
  'et',
  'eu',
  'fi',
  'fj',
  'fk',
  'fm',
  'fo',
  'fr',
  'ga',
  'gb',
  'gb-eng',
  'gb-nir',
  'gb-sct',
  'gb-wls',
  'gd',
  'ge',
  'gf',
  'gh',
  'gi',
  'gl',
  'gm',
  'gn',
  'gp',
  'gq',
  'gr',
  'gt',
  'gu',
  'gw',
  'gy',
  'hk',
  'hn',
  'hr',
  'ht',
  'hu',
  'id',
  'ie',
  'il',
  'im',
  'in',
  'iq',
  'ir',
  'is',
  'it',
  'je',
  'jm',
  'jo',
  'jp',
  'jr',
  'ke',
  'kg',
  'kh',
  'ki',
  'km',
  'kn',
  'kp',
  'kr',
  'kw',
  'ky',
  'kz',
  'la',
  'lb',
  'lc',
  'li',
  'lk',
  'lr',
  'ls',
  'lt',
  'lu',
  'lv',
  'ly',
  'ma',
  'mc',
  'md',
  'me',
  'mg',
  'mh',
  'mk',
  'ml',
  'mm',
  'mn',
  'mo',
  'mp',
  'mq',
  'mr',
  'ms',
  'mt',
  'mu',
  'mv',
  'mw',
  'mx',
  'my',
  'mz',
  'na',
  'nc',
  'ne',
  'nf',
  'ng',
  'ni',
  'nl',
  'no',
  'np',
  'nr',
  'nu',
  'nz',
  'oly',
  'om',
  'pa',
  'pe',
  'pf',
  'pg',
  'ph',
  'pk',
  'pl',
  'pm',
  'pr',
  'ps',
  'pt',
  'pw',
  'py',
  'qa',
  're',
  'ro',
  'rs',
  'ru',
  'rw',
  'sa',
  'sb',
  'sc',
  'sd',
  'se',
  'sg',
  'sh',
  'si',
  'sk',
  'sl',
  'sm',
  'sn',
  'so',
  'sr',
  'ss',
  'st',
  'sv',
  'sx',
  'sy',
  'sz',
  'tc',
  'td',
  'tg',
  'th',
  'tj',
  'tk',
  'tl',
  'tm',
  'tn',
  'to',
  'tr',
  'tt',
  'tv',
  'tw',
  'tz',
  'ua',
  'ug',
  'un',
  'us',
  'uy',
  'uz',
  'va',
  'vc',
  've',
  'vg',
  'vi',
  'vn',
  'vu',
  'wf',
  'ws',
  'xk',
  'ye',
  'yt',
  'za',
  'zm',
  'zw',
]
